apiVersion: v1
kind: ServiceAccount
metadata:
  name: pxc-auto-recover
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pxc-auto-recover-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pxc-auto-recover-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pxc-auto-recover-role
subjects:
  - kind: ServiceAccount
    name: pxc-auto-recover
    namespace: default
